spring:
  application:
    name: ludotheque
  datasource:
    url: jdbc:sqlserver://10.1.200.24;databasename=LUDO_DB;integratedSecurity=false;encrypt=false;trustServerCertificate=false
    username: LUDO_USER
    password: LUDO_PWD85260
  jpa:
    show-sql: true

# Configuration Swagger/OpenAPI
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    resolve-schema-properties: true
    group-configs:
      - group: public
        display-name: API Ludothèque
        paths-to-match: /**
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  server:
    adress: 10.1.200.24
    port : 8080
